live_config_reload = true

[font]
size = 11.0

[font.normal]
family = "MesloLGL Nerd Font Mono"

[font.offset]
x = 1

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
startup_mode = "Fullscreen"

opacity = 0.9
blur = true
