# frozen_string_literal: true

# vi:ft=ruby:

tap "aws/tap"
tap "itchyny/tap" # git-branch-name
tap "thoughtbot/formulae" # rcm
tap "universal-ctags/universal-ctags"

# Utils
brew "ag"
brew "aws-sam-cli"
brew "awscli"
brew "bandwhich"
brew "bat"
brew "carthage" # Dependencies for Cocoa
brew "cmake"
brew "colima"
brew "direnv"
brew "docker"
brew "efm-langserver"
brew "elixir"
brew "entr"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-branch-name"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jq"
brew "lima"
brew "lua-language-server"
brew "marksman" # markdown language server
brew "neovim"
brew "pinentry-mac"
brew "qemu"
brew "rcm"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruff"
brew "rust-analyzer"
brew "shellcheck"
brew "shfmt"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "tree"
brew "unison"
brew "uv"
brew "watch"
brew "wget"
brew "wireguard-tools"
brew "yaml-language-server"
brew "yarn"
brew "yq"
brew "yt-dlp"
brew "zlib"
brew "zoxide"

# Garbage Heap?
# brew "docker-compose"
# brew "docker-machine"
# brew "gdb" not available on apple silicon
# brew "gnupg21"
# brew "nerdctl"
# brew "universal-ctags"
# brew "willgit"

# Applications
cask "alacritty"
cask "firefox"
cask "gpg-suite"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "ngrok"
cask "obsidian"
cask "gitx"
cask "transmission"
cask "utm"
cask "vagrant"
# cask "virtualbox-beta"
# cask "virtualbox-extension-pack-beta"
# cask "slack"

# Garbage Heap?
# cask "dash"
# cask "google-chrome"
# cask "macfuse"
# cask "osxfuse"
# cask "psequel"
# cask "sequel-pro"
# cask "xquartz"
# cask "zoom"
