# frozen_string_literal: true

# vi:ft=ruby:
tap "homebrew/cask"
tap "homebrew/services"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"

# Utils
brew "asdf"
brew "pyenv"
brew "rbenv"

# brew "awscli"
# brew "gnupg21"
brew "ag"
brew "bat"
brew "cmake"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "elixir"
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "fish"
brew "fzf"
brew "git"
brew "gnupg"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "neovim", args: %w[HEAD]
brew "node"
brew "pinentry-mac"
brew "rcm"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "universal-ctags"
brew "watch"
brew "wget"
brew "willgit"
brew "yarn"
brew "youtube-dl"
brew "zlib"


# Applications
# cask "psequel"
cask "alacritty"
cask "dash"
cask "firefox"
cask "google-chrome"
cask "gpg-suite"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "rowanj-gitx"
cask "sequel-pro"
cask "slack"
cask "transmission"
cask "virtualbox"
cask "xquartz"
cask "zoom"
