#!/usr/bin/env zsh

# check if fasd is installed
if (( ${+commands[fasd]} )); then
  fasd_cache="${ZSH_CACHE_DIR}/fasd-init-cache"
  if [[ "$commands[fasd]" -nt "$fasd_cache" || ! -s "$fasd_cache" ]]; then
    fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install \
      zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
  fi
  source "$fasd_cache"
  unset fasd_cache

  alias v='f -e "$EDITOR"'
  alias o='a -e xdg-open'
  alias j='zz'
fi

# check if fasder is installed (macOs)
if (( ${+commands[fasder]} )); then
  alias fasd="fasder"

  fasd_cache="${ZSH_CACHE_DIR}/fasd-init-cache"
  if [[ "$commands[fasder]" -nt "$fasd_cache" || ! -s "$fasd_cache" ]]; then
    fasd --init auto aliases >| "$fasd_cache"
  fi
  source "$fasd_cache"
  unset fasd_cache
fi


