#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom -f -D 3 -I 1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap		 0
#bspc config focused_border_color \#3c3836
#bspc config normal_border_color \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a polybar border=off manage=off
bspc rule -a sxiv state=floating center=true

$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/wallpaper.jpg &
