#!/usr/bin/env bash

set -e

echo "Installing Rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y

echo "Installing Cargo Packages"
PACKAGES=(
  taplo-cli
  wasm-pack
)
cargo install "${PACKAGES[@]}"
