#!/usr/bin/env bash

set -e

echo "Installing Global RubyGems"

GEMS=(
  bundler
  interactive_editor
  reek
  rubocop
  rubocop-performance
  rubocop-rails
  rubocop-rspec
  ruby-lint
  ruumba
  solargraph
  tmuxinator
)

gem install --conservative "${GEMS[@]}"
