#!/usr/bin/env bash

set -e

echo "Installing NPM Packages"

npm i -g npm

PACKAGES=(
  babel-eslint
  bash-language-server
  dockerfile-language-server-nodejs
  eslint
  eslint-plugin-react
  js-yaml
  mermaid
  neovim
  standard
  svgo
  typescript
  typescript-eslint-parser
  typescript-language-server
  vscode-langservers-extracted
  wscat
  yaml-language-server
)

npm install -g "${PACKAGES[@]}"
