#!/usr/bin/env bash

set -e

echo "Install Global pip Packages"

PACKAGES=(
  neovim
  pynvim
  'python-lsp-server[all]'
  pylsp-mypy
  black
  isort
  pyright
  ruff
)

pip3 install "${PACKAGES[@]}"
