[tools]
bun = "latest"
cargo-binstall = "latest"
go = "1.24"
node = "24"
python = "3.13"
ruby = "3.4"
rust = "latest"

# Python Global Packages
"pipx:pyright" = "latest"
"pipx:python-lsp-server[all]" = "latest"

# Node Global Packages
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:svgo" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:wscat" = "latest"

# Cargo Global Packages
"cargo:taplo-cli" = "latest"
"cargo:unison-fsmonitor" = "latest"
"cargo:wasm-pack" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python", "node"]

# Still experimental:
# [settings.python]
# uv_venv_auto = true

[settings.npm]
bun = true

[settings.pipx]
uvx = true
