name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      MISE_GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@main
      - name: link dotfiles to home directory
        run: ln -s "$GITHUB_WORKSPACE" "$HOME/.dotfiles"
      - name: install
        run: bash ./install.sh
